server:
  port: 8086

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fish_recommend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: secu
    password: secu123

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create